### ISSUE TITLE
Size of ID

### ISSUE THREAD

**Issue by eekorka** [Aj-Seven/backend-projects#1]
Hello. You create new ID like max ID + 1. But if you delete task with ID lower than max, this ID isn't reusable. You still give ID more than max ID in your list. The size of your IDs will become more and more. If i understood it right. I'm beginner and just want to understand.

**Comment by aj-seven** [comment]
Yes you are correct, If we delete the old id's task it isn't useful. Seems, that function needed an update.
Thanks for review. Well you can make changes to this...

**Comment by eekorka** [comment]
Thanks for your answer. I'm still thinking about the perfect solution.

**Comment by aj-seven** [comment]
Issue resolved, Now the deleted id's are re-usable too 🎉
