### ISSUE TITLE
Command-line interface logic

### ISSUE THREAD

**Issue by yeetdevDave** [Aj-Seven/backend-projects#2]
I'll give an example

If I run `node index.js foo 6 bar delete` I will be able to delete even though it doesn't match the syntax `node index.js delete id`

And this is true for other actions also i.e. add, list, update, delete, etc.

This is because we're only checking if the action e.g. delete is included in the array of arguments. Instead, we should do it based on position.

**Comment by aj-seven** [comment]
Thanks for your review, I will check and update it. 😃

**Comment by aj-seven** [comment]
Issue is resolved. 👍
